# Generated by Django 6.1 on 2026-08-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('watched', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='movies.movie')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_movies', to='playlists.playlist')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='playlists', through='playlists.PlaylistMovie', to='movies.movie'),
        ),
        migrations.AddIndex(
            model_name='playlistmovie',
            index=models.Index(fields=['playlist', 'position'], name='playlists_p_playlis_e76dc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistmovie',
            unique_together={('playlist', 'movie')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user'], name='playlists_p_user_id_db834d_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['is_public'], name='playlists_p_is_publ_701ac5_idx'),
        ),
    ]
